# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  ghcr: # Define access for a private registry
    type: docker-registry
    url: ghcr.io
    username: ChildMindInstituteCNL  # machine user
    password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
updates:
- package-ecosystem: github-actions  # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  directory: /
  registries: '*'
  schedule:
    interval: monthly
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  groups:
    production dependencies:
      dependency-type: production
    development dependencies:
      dependency-type: development
  registries: '*'
  target-branch: develop
