[project]
name = "cpac"
description = "C-PAC Python Package"
authors = [{name = "C-PAC developers", email = "cpac@cnl.childmind.org"}]
license = "MIT"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Bio-Informatics"
]
requires-python = ">=3.10,<4.0"
dependencies = [
  "docker>=7.1.0",
  "dockerpty",
  "docker-pycreds",
  "pandas>=0.23.4",
  "poetry>=2.0.0",
  "pyyaml",
  "rich",
  "semver",
  "spython>=0.3.0",
  "tabulate>=0.8.6",
  "tomli; python_version < '3.11'",
  "tornado",
  "websocket-client"
]
readme = "README.rst"
version = "1.8.8.dev1"

[project.optional-dependencies]
dev = ["coveralls", "pytest", "pytest-remotedata>=0.3.2", "pytest-runner", "sphinx"]
gradients = []
testing = ["alabaster", "imagesize", "pytest", "pytest-cov", "pytest-runner", "sphinx"]
tsconcat = [
  "ba-tsconcat>=0.1.2,<0.2.0; python_version >= '3.11' and python_version < '4.0'",
  "bids2table==0.1.0",
  "elbow==0.1.1",
  "imagesize",
  "nibabel==5.3.2",
  "numpy>=1.26.3,<2.0.0",
  "pandas==2.2.2",
  "pyarrow==18.1.0"
]

[project.scripts]
cpac = "cpac.__main__:run"

[project.urls]
documentation = "https://fcp-indi.github.io/docs/latest/user/cpac"
repository = "https://github.com/FCP-INDI/cpac"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.aliases]
build = "poetry build"
release = "poetry publish"
test = "pytest"

[tool.coverage.run]
branch = true
relative_files = true
omit = [
  # runs in container so unseen by coverage
  "src/cpac/helpers/cpac_read_crash.py"
]

[tool.coverage.paths]
source = [
  "src/",
  "*/site-packages/"
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
  # Standard pragma
  "pragma: no cover",
  # Don't complain about missing debug-only code:
  "def __repr__",
  "if self\\.debug",
  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",
  # Don't complain if non-runnable code isn't run:
  "if 0:",
  "if __name__ == .__main__.:"
]

[tool.devpi.upload]
no-vcs = "1"
formats = "bdist_wheel"

[tool.poetry]
requires-poetry = ">=2.0"

[tool.pytest.ini_options]
addopts = "-s"
# --cov cpac --cov-report term-missing -s
# -s
# --verbose
norecursedirs = [
  "dist",
  "build",
  ".tox"
]
testpaths = ["tests"]

[tool.ruff]
extend-exclude = ["docs/conf.py"]
target-version = "py38"

[tool.ruff.lint]
extend-select = ["A", "C4", "D", "G", "I", "ICN", "NPY", "PL", "RET", "RSE", "RUF", "Q", "W"]

[tool.ruff.lint.isort]
combine-as-imports = true
extra-standard-library = ["tomllib"]
force-sort-within-sections = true
known-first-party = ["cpac"]
no-lines-before = ["collab", "other-first-party", "local-folder"]
order-by-type = false
section-order = ["future", "standard-library", "third-party", "collab", "other-first-party", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
"collab" = ["nipype", "spython"]
"other-first-party" = ["ba_timeseries_gradients", "bids2table", "tsconcat"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.pylint]
max-args = 10
max-branches = 50
max-returns = 12
max-statements = 100

[tool.ruff.lint.pyupgrade]
# Until variants Python ≥ 3.10
keep-runtime-typing = true
